Security API for CCP: SHA256 Class Reference
SHA256 Class Reference
SHA256 class.
#include <sha256.hpp>
Public Member Functions
void init ()
Function used to init the hash module.
void update (const uint8_t *data, size_t length)
Function used to add data-block to the processed input.
void final (uint8_t hash[32])
Function used to finalize the hash procedure.
Static Public Member Functions
static myerror_t test ()
Auto test function to test SHA-256 implementation w.r. to few test vectors.
Static Public Attributes
static const size_t hashSize = 32
static const size_t blockSize = 64
Private Member Functions
void compress (const uint8_t data[64])
SHA-256 compression function.
Private Attributes
uint32_t state [8]
State of the hash process.
uint64_t dataBitLength
Number of bits processed by the hash function.
uint8_t dataBuffer [64]
Data buffer used before enough bytes (64) are available.
size_t bufferLength
Current number of bytes in the data buffer.
Static Private Attributes
static const uint32_t k [64]
Constants for the compression function.
static const size_t TV_lengths [4]
Lengths of test vectors.
static const char * TV_messages [4]
Messages used in test vectors.
static const uint8_t TV_hashes [4][32]
Hashes obtained for test vectors.
Detailed Description
Definition at line 16 of file sha256.hpp.
Member Function Documentation
void SHA256::final (uint8_t hash[32])
This function stores in the parameter the output of the hashing process applied to the data blocks provided by the calls to the update function.
Parameters
hash is a 32-byte array that will contain the final hash value.
Referenced by User::hashPassword().
void SHA256::init ()
This function inits the hash module by reseting the state to initial values.
Referenced by User::hashPassword().
static myerror_t SHA256::test () static
This function uses test vectors defined in the class and test implementation versus them.
Returns
ERROR_UNEXPECTED if a mismatch is found
NO_ERROR if everything matches
void SHA256::update (const uint8_t * data, size_t length)
This function process the provided data but outputs nothing. Multiple call to update may be of interest when data is being received in multiple blocks or if the message is too large or the memory.
Parameters
data is an array of bytes to process.
length is the number of element in the array data.
Referenced by User::hashPassword().
The documentation for this class was generated from the following file:
includes/sha256.hpp