Security API for CCP: Key Class Reference
Key Class Reference
Key class.
#include <key.hpp>
Public Member Functions
Key ()
Default constructor: used to create an empty Key before updating it from a JSON string for instance.
~Key ()
Key destructor.
myerror_t set (const std::string &field, const std::string &value)
This function set the given attribute to the provided value in class Key.
uint32_t getId () const
Function returning the id of the key.
uint32_t getOwner () const
Function returning the owner of the key.
key_type_t getType () const
Function returning the type of the key.
key_use_t getUse () const
Function returning the usage of the key.
date_t getValidity () const
Function returning the validity period of the key.
std::vector< uint8_t > getValue () const
Function returning the (encrypted) value of the key.
myerror_t serialize (uint8_t *tab, size_t len)
Serialize the Key object to a byte array of _serializedUserSize bytes.
Data Fields
uint32_t _associated
If the corresponding private/public key is in the database: contains its id.
size_t _length
Number of bytes of the key.
Static Public Attributes
static const size_t _serializedSize = 4 + 4 + 1 + 1 + 4 + 4 + sizeof(size_t)
Size of the serialization of a Key object without its value.
Private Attributes
uint32_t _id
Id of the key, must be unique.
uint32_t _owner
Id of the key owner.
key_type_t _type
Type of the key.
key_use_t _use
Use of the key.
date_t _validity
Date when the key will not be valid anymore.
std::vector< uint8_t > _value
Value of the key.
Friends
class API
Detailed Description
Definition at line 46 of file key.hpp.
Constructor & Destructor Documentation
Key::Key () inline
Definition at line 54 of file key.hpp.
Key::~Key () inline
Definition at line 59 of file key.hpp.
Member Function Documentation
uint32_t Key::getId () const
Definition at line 7 of file key.cpp.
References _id.
Referenced by operator<<().
uint32_t Key::getOwner () const
Definition at line 12 of file key.cpp.
References _owner.
Referenced by API::decrypt(), API::encrypt(), operator<<(), API::unwrap(), and API::wrap().
key_type_t Key::getType () const
Definition at line 17 of file key.cpp.
References _type.
Referenced by API::decrypt(), API::encrypt(), and operator<<().
key_use_t Key::getUse () const
Definition at line 22 of file key.cpp.
References _use.
Referenced by API::decrypt(), API::encrypt(), operator<<(), API::unwrap(), and API::wrap().
date_t Key::getValidity () const
Definition at line 27 of file key.cpp.
References _validity.
Referenced by operator<<().
std::vector< uint8_t > Key::getValue () const
Definition at line 32 of file key.cpp.
References _value.
Referenced by API::decryptKey(), and operator<<().
myerror_t Key::set (const std::string & field, const std::string & value)
This function is for example used to construct Key classes from a json_object_t.
Parameters
field is a string containing the name of the attribute
value is the value that should be set to the mentioned attribute.
Returns
NO_ERROR if no error occured
Definition at line 61 of file key.cpp.
References _associated, _id, _length, _owner, _type, _use, _validity, _value, and BASE64::decode().
The documentation for this class was generated from the following files:
includes/key.hpp
src/key.cpp