Security API for CCP: API Class Reference
API Class Reference
API class.
#include <api.hpp>
Public Member Functions
API (const char *fileUsers, const char *fileKeys)
The constructor initialises API from the file given in parameter.
~API ()
The API destructor.
void reset ()
Resets the API.
myerror_t newUser (const std::string &login, const std::string &password, uint32_t *id)
Register a new user to the API.
myerror_t deleteUser (uint32_t id)
Delete the user from the API.
myerror_t newKey (key_type_t type, key_use_t use, date_t validity, size_t length, uint32_t *id)
Randomly generate a key and add it to the memory.
myerror_t disconnect ()
myerror_t connectUser (const std::string &login, const std::string &password)
myerror_t wrap (uint32_t idWrapKey, uint32_t idExportedKey, uint8_t *output, size_t *length)
myerror_t unwrap (uint32_t idWrapKey, uint8_t *importedKey, size_t length, key_type_t type, key_use_t use, date_t validity, uint32_t *id)
myerror_t encrypt (uint32_t idKey, uint8_t *buffer, size_t length)
myerror_t decrypt (uint32_t idKey, uint8_t *buffer, size_t length)
Static Public Member Functions
static void initFile (const char *fileUsers, const char *fileKeys, unsigned instanceId)
Init a file corresponding to a void API object.
Private Member Functions
myerror_t addKey (Key *key)
Add a key to the memory.
myerror_t addUser (User *user)
Add a user to the base.
myerror_t saveAPI ()
This function stores the data into the file API::filename.
myerror_t loadAPI ()
This function loads the protected data contained in the file API::filename.
myerror_t findKey (uint32_t id, Key **key)
This function finds a key corresponding to a given id.
myerror_t decryptKey (const Key *key, uint8_t *output, size_t *length)
This function decrypts the key using the local encryption key. IMPORTANT: erase buffer after use !
myerror_t protectData (uint8_t *data, size_t length)
This function encrypts the data using the local encryption key.
Private Attributes
uint32_t _instanceId
Id of the API instance (used to identify this instance and to ensure user and key files are corresponding to the same instance.
bool _isInit
Boolean variable set to true only once memory have been initialised by loading a file.
User * _connectedUser
Identity of the currently connected user (0 if no user connected).
std::string _fileUsers
Variable containing the relative path and filename of the file from which the user memory got initialised and where it should be saved on exit.
std::string _fileKeys
Variable containing the relative path and filename of the file from which the key memory got initialised and where it should be saved on exit.
std::vector< User * > _users
List of registered users.
std::vector< Key * > _keys
Memory containing all keys that may be manipulated by the API.
Detailed Description
Definition at line 17 of file api.hpp.
Constructor & Destructor Documentation
API::API (const char * fileUsers, const char * fileKeys)
Parameters
filename string containing the relative path and filename of the file containing the protected memory content to load.
Check that the user file exists
Check that the key file exists
If yes copy filenames to API::fileUsers and API::fileKeys
Call API::loadAPI() to load data from the file
Test return code and set API::isInit in case of success
Definition at line 9 of file api_ext.cpp.
References _fileKeys, _fileUsers, _isInit, loadAPI(), and NO_ERROR.
API::~API ()
Automatically dump current API memory to the file used for constructing the object.
Do nothing if API is not initialized
Dump API to the file API::filename
Free all classes using reset() function.
Definition at line 46 of file api_ext.cpp.
References _isInit, reset(), and saveAPI().
Member Function Documentation
myerror_t API::addKey (Key * key) private
Parameters
key is a pointer to the Key class that should be added to the memory.
Returns
NO_ERROR
Definition at line 334 of file api_int.cpp.
References _keys, and NO_ERROR.
Referenced by loadAPI(), newKey(), and unwrap().
myerror_t API::addUser (User * user) private
Add the user to the list of API users.
Parameters
user is a pointer to the User class that should be registered.
Returns
NO_ERROR if no error occured
ERROR_PARAM if user is already in the base
Definition at line 340 of file api_int.cpp.
References _users, ERROR_PARAM, User::hasSameLogin(), and NO_ERROR.
Referenced by loadAPI(), newUser(), and reset().
myerror_t API::decrypt (uint32_t idKey, uint8_t * buffer, size_t length)
Get the key
Test that the connected user owns the key
Test key use and type
Encrypt
Definition at line 492 of file api_ext.cpp.
References _connectedUser, AES::decrypt(), decryptKey(), ERROR_PARAM, ERROR_SEC, findKey(), User::getId(), Key::getOwner(), Key::getType(), Key::getUse(), KEY_ENCR, KEY_SYM, MAX_KEY_LEN, and NO_ERROR.
myerror_t API::decryptKey (const Key * key, uint8_t * output, size_t * length) private
Parameters
key is a pointer to the key to decrypt
output will contain the key value
length is a pointer to the length of the byte array that will be set to the final size of the wrapped key.
Returns
NO_ERROR if no error occured
ERROR_PARAM if ouptut is too small
Definition at line 377 of file api_int.cpp.
References Key::_length, AES::decrypt(), ERROR_PARAM, ERROR_UNEXPECTED, Key::getValue(), and NO_ERROR.
Referenced by decrypt(), encrypt(), unwrap(), and wrap().
myerror_t API::deleteUser (uint32_t id)
Deleting a user from the user list (admin rights required).
Parameters
id is the id of the user to delete
Returns
NO_ERROR if no error occured
ERROR_SEC if connected user is not admin or if he tries to delete himself
ERROR_PARAM if user is not in the base
Definition at line 126 of file api_ext.cpp.
References _connectedUser, _keys, _users, ERROR_PARAM, ERROR_SEC, ERROR_SEQ, User::getRole(), NO_ERROR, and USER_ADMIN.
myerror_t API::encrypt (uint32_t idKey, uint8_t * buffer, size_t length)
Get the key
Test that the connected user owns the key
Test key use and type
Encrypt
Definition at line 437 of file api_ext.cpp.
References _connectedUser, decryptKey(), AES::encrypt(), ERROR_PARAM, ERROR_SEC, findKey(), User::getId(), Key::getOwner(), Key::getType(), Key::getUse(), KEY_ENCR, KEY_SYM, MAX_KEY_LEN, and NO_ERROR.
myerror_t API::findKey (uint32_t id, Key ** key) private
Parameters
id is the id of the searched key
key is a pointer to a key* object that will be set to point to the found key
Returns
NO_ERROR if no error occured
ERROR_PARAM if no key is found
Definition at line 358 of file api_int.cpp.
References _keys, ERROR_PARAM, and NO_ERROR.
Referenced by decrypt(), encrypt(), unwrap(), and wrap().
void API::initFile (const char * fileUsers, const char * fileKeys, unsigned instanceId) static
Format a file to be a void API object.
Definition at line 547 of file api_ext.cpp.
myerror_t API::loadAPI () private
Returns
NO_ERROR if no error occured
ERROR_IO if an error occured when reading the file
ERROR_FORMAT if an error occured when parsing the data
Opening the user file
Reading header
Init tag computation
Reading users
Adding to tag computation
Compute the tag corresponding to the file
Opening the key file
Reading header
Init tag computation
Reading keys
Adding to tag computation
Compute the tag corresponding to the file
Closing the file
Definition at line 129 of file api_int.cpp.
References _fileKeys, _fileUsers, _instanceId, _isInit, User::_serializedSize, Key::_serializedSize, addKey(), addUser(), BASE64::decode(), ERROR_FORMAT, ERROR_IO, ERROR_SEC, HMAC::final(), HMAC::init(), MAX_KEY_LEN, newKey(), newUser(), NO_ERROR, reset(), and HMAC::update().
Referenced by API().
myerror_t API::newKey (key_type_t type, key_use_t use, date_t validity, size_t length, uint32_t * id)
Parameters
type should be one of the key_type_t values
use should be one of the key_use_t values
validity could be anything
length should not be 0 and should not exceed the maximal size of a key MAX_KEY_LEN
id will be set to 0 in case of error or will contain the newly created key id (could be NULL)
Returns
NO_ERROR if no error occured
ERROR_PARAM if invalid attributes are given
Only symmetric keys are implemented at the moment
Check key size
Check use
Setting attributes
Generating the value
Definition at line 180 of file api_ext.cpp.
References Key::_associated, _connectedUser, Key::_id, _keys, Key::_length, Key::_owner, Key::_type, Key::_use, Key::_validity, Key::_value, addKey(), ERROR_PARAM, User::getId(), KEY_ENCR, KEY_INTE, KEY_SIGN, KEY_SYM, KEY_WRAP, MAX_KEY_LEN, and NO_ERROR.
Referenced by loadAPI().
myerror_t API::newUser (const std::string & login, const std::string & password, uint32_t * id)
Add the user to the list of API users.
Parameters
login is a string containing the login of the user to create
password contains the corresponding password
id is a pointer to a variable that will get the id of the created user or be set to 0 in case of error (id could be NULL)
Returns
NO_ERROR if no error occured
ERROR_SEC if current user has not admin rights
ERROR_SEQ if nobody is connected
ERROR_PARAM if user is already in the base
Definition at line 82 of file api_ext.cpp.
References _connectedUser, _users, addUser(), ERROR_PARAM, ERROR_SEC, ERROR_SEQ, User::getId(), User::getRole(), NO_ERROR, USER_ADMIN, and USER_BASIC.
Referenced by loadAPI().
myerror_t API::protectData (uint8_t * data, size_t length) private
Parameters
data is a pointer to the data to protect
length is the length of the data (in bytes).
Returns
NO_ERROR if no error occured
Definition at line 414 of file api_int.cpp.
References AES::encrypt(), ERROR_UNEXPECTED, and NO_ERROR.
Referenced by unwrap().
void API::reset ()
Resets the API by deleting users and memory. An admin account is created with default password s3cr3t_p
Definition at line 60 of file api_ext.cpp.
References _connectedUser, _keys, _users, addUser(), NO_ERROR, and USER_ADMIN.
Referenced by loadAPI(), and ~API().
myerror_t API::saveAPI () private
Returns
NO_ERROR if no error occured
ERROR_IO if an error occured when writing in the file
Opening the user file
Init tag computation
Processing the header
Printing
Adding to tag computation
Processing the users
Printing
Adding to tag computation
Next key
Dumping the footer
Close the file
Opening the key file
Init tag computation
Processing the header
Printing
Adding to tag computation
Dumping keys
Adding to tag computation
Next key
Dumping the footer
Close the file
Definition at line 15 of file api_int.cpp.
References _fileKeys, _fileUsers, _instanceId, _keys, User::_serializedSize, Key::_serializedSize, _users, BASE64::encode(), ERROR_IO, HMAC::final(), HMAC::init(), MAX_KEY_LEN, NO_ERROR, and HMAC::update().
Referenced by ~API().
myerror_t API::unwrap (uint32_t idWrapKey, uint8_t * importedKey, size_t length, key_type_t type, key_use_t use, date_t validity, uint32_t * id)
Get the key
Test that the connected user owns the key
Test wrap key use and import size
Unwrap key and protect it with local key
Add key to API
Setting attributes
Definition at line 359 of file api_ext.cpp.
References Key::_associated, _connectedUser, Key::_id, _keys, Key::_length, Key::_owner, Key::_type, Key::_use, Key::_validity, Key::_value, addKey(), AES::decrypt(), decryptKey(), ERROR_PARAM, ERROR_SEC, findKey(), User::getId(), Key::getOwner(), Key::getUse(), KEY_WRAP, MAX_KEY_LEN, NO_ERROR, protectData(), and wrap().
myerror_t API::wrap (uint32_t idWrapKey, uint32_t idExportedKey, uint8_t * output, size_t * length)
Get the keys
Test that the connected user owns the keys
Test wrap key use and output size
Wrap key
Definition at line 297 of file api_ext.cpp.
References _connectedUser, decryptKey(), AES::encrypt(), ERROR_PARAM, ERROR_SEC, findKey(), User::getId(), Key::getOwner(), Key::getUse(), KEY_WRAP, MAX_KEY_LEN, and NO_ERROR.
Referenced by unwrap().
The documentation for this class was generated from the following files:
includes/api.hpp
src/api_ext.cpp
src/api_int.cpp