Security API for CCP: Object Class Reference
Object Class Reference
Class Object: class of all objects in the memory.
#include <object.hpp>
Public Member Functions
myerror_t dump (uint8_t **pointer, size_t *size)
This function serialize the Object class into an array of bytes.
void addAttribute (bool value)
Add a boolean attribute to the Object.
void addAttribute (unsigned value)
Add an 32-bit unsigned integer attribute to the Object.
Static Public Member Functions
static myerror_t parse (uint8_t *buffer, Object **res)
This function parse a buffer to create an Object class.
Data Fields
const type_t type
Type of the Object.
uint8_t * value
Value of the Object.
uint32_t valueLen
Byte length of the Object value.
Private Attributes
std::vector< bool > booleanAttributes
Object boolean attributes.
std::vector< uint32_t > unsignedAttributes
Object unsigned integers attributes (32-bit).
Detailed Description
Definition at line 29 of file object.hpp.
Member Function Documentation
void Object::addAttribute (bool value)
Parameters
value is the value of the new attribute. There is no room for an attribute name: the index in the attribute vector determines to which attribute the value corresponds.
Definition at line 115 of file object.cpp.
References booleanAttributes.
Referenced by parse().
void Object::addAttribute (unsigned value)
Parameters
value is the value of the new attribute. There is no room for an attribute name: the index in the attribute vector determines to which attribute the value corresponds.
Definition at line 120 of file object.cpp.
References unsignedAttributes.
myerror_t Object::dump (uint8_t ** pointer, size_t * size)
This function is for example used to dump an Object class when saving the API in a file.
Parameters
pointer is a pointer to the buffer that will contain the result. *pointer should be initialised to NULL since the memory allocation will be done by the function.
size is a pointer to an integer that which value will be set to the actual size of the allocated buffer.
Returns
NO_ERROR if no error occured
ERROR_PARAM if pointer is NULL or *pointer is not NULL
Definition at line 15 of file object.cpp.
References booleanAttributes, ERROR_PARAM, NO_ERROR, unsignedAttributes, value, and valueLen.
myerror_t Object::parse (uint8_t * buffer, Object ** res) static
This function is for example used to construct Object classes when loading the API from a file.
Parameters
buffer is the byte array from which data will be read.
res is a pointer to the User pointer that will contain the result. *pointer should be initialised to NULL since the memory allocation will be done by the function.
Returns
NO_ERROR if no error occured
ERROR_PARAM if res is NULL or *res is not NULL
Definition at line 63 of file object.cpp.
References addAttribute(), ERROR_MEM, ERROR_PARAM, NO_ERROR, value, and valueLen.
Referenced by API::loadAPI().
The documentation for this class was generated from the following files:
includes/object.hpp
src/object.cpp