Security API for CCP: HMAC Class Reference
HMAC Class Reference
HMAC class.
#include <hmac.hpp>
Public Member Functions
void init (const uint8_t *key, size_t length)
Function used to init the mac module.
void update (const uint8_t *data, size_t length)
Function used to add data-block to the processed input.
void final (uint8_t *tag)
Function used to finalize the mac procedure.
Static Public Member Functions
static myerror_t test ()
Auto test function to test HMAC implementation w.r. to few test vectors (SHA-256).
Static Public Attributes
static constexpr size_t tagLength = 32
Private Attributes
SHA256 * hashFunction
Hash function used.
size_t keyLength
Length of the key used.
const uint8_t * keyValue
Key used.
Static Private Attributes
static const uint8_t ipad
Constant used for inner padding.
static const uint8_t opad
Constant used for outer padding.
static const size_t TV_klengths [3]
Lengths of test vectorkeys.
static const uint8_t TV_keys [3][256]
Keys used in test vectors.
static const size_t TV_mlengths [3]
Lengths of test vector messages.
static const uint8_t TV_messages [3][128]
Messages used in test vectors.
static const uint8_t TV_tags [3][tagLength]
Hashes obtained for test vectors.
Detailed Description
At the moment uses SHA-256 hash function but should be init with any hash function in a future implementation.
Definition at line 18 of file hmac.hpp.
Member Function Documentation
void HMAC::final (uint8_t * tag)
This function stores in the parameter the tag computed from the data blocks provided by the calls to the update function.
Parameters
hash is an array that will contain the final tag value. Enough space should have been allocated to contain the tag value which size depends on the hash function used.
Referenced by API::loadAPI(), and API::saveAPI().
void HMAC::init (const uint8_t * key, size_t length)
This function inits the hash module and starts hashing the key xored to ipad.
Parameters
key is an array of bytes containing the integrity key.
length is the number key bytes.
Referenced by API::loadAPI(), and API::saveAPI().
static myerror_t HMAC::test () static
This function uses test vectors defined in the class and test implementation versus them.
Returns
ERROR_UNEXPECTED if a mismatch is found
NO_ERROR if everything matches
void HMAC::update (const uint8_t * data, size_t length)
This function process the provided data but outputs nothing. Multiple call to update may be of interest when data is being received in multiple blocks or if the message is too large or the memory.
Parameters
data is an array of bytes to process.
length is the number of element in the array data.
Referenced by API::loadAPI(), and API::saveAPI().
The documentation for this class was generated from the following file:
includes/hmac.hpp