Security API for CCP: includes/key.hpp File Reference
key.hpp File Reference
#include <cstdint>
#include <cstdlib>
#include <iostream>
#include <vector>
#include "error.hpp"
Data Structures
class Key
Key class.
Typedefs
typedef uint32_t date_t
Enumerations
enum key_type_t { KEY_SYM = 1, KEY_PUB = 2, KEY_PRI = 3 }
Key types.
enum key_use_t { KEY_ENCR = 1, KEY_SIGN = 2, KEY_INTE = 3, KEY_WRAP = 4 }
Key use.
Functions
std::ostream & operator<< (std::ostream &os, const Key &obj)
This function serializes the Key class into a JSON format string.
std::istream & operator>> (std::istream &is, Key &obj)
This function parses a string in JSON format to update a Key class.
Variables
constexpr unsigned MAX_KEY_LEN = 64
Maximum length of a key.
Detailed Description
Key definition
Key class definition.
Definition in file key.hpp.
Enumeration Type Documentation
enum key_type_t
Enumerator
KEY_SYM
symmetric key
KEY_PUB
public key
KEY_PRI
private key
Definition at line 20 of file key.hpp.
enum key_use_t
Enumerator
KEY_ENCR
encryption/decryption key (for data)
KEY_SIGN
signature key (for data)
KEY_INTE
integrity key (for data)
KEY_WRAP
wrapping key (for keys)
Definition at line 30 of file key.hpp.
Function Documentation
std::ostream& operator<< (std::ostream & os, const Key & obj)
This function is for example used to dump a Key class when saving the API in a file.
Parameters
os is an output stream in which will be send the serialized User.
obj is the Key object to serialize.
Returns
the output stream given as argument.
Definition at line 37 of file key.cpp.
References Key::_associated, Key::_length, BASE64::encode(), Key::getId(), Key::getOwner(), Key::getType(), Key::getUse(), Key::getValidity(), Key::getValue(), and KEY_SYM.
std::istream& operator>> (std::istream & is, Key & obj)
This function is for example used to construct Key classes when loading the API from a file.
Parameters
is is an input stream from which the serialization of the User will be taken.
obj is the Key object that will contain the constructed User.
Returns
the input stream given as argument.
Definition at line 118 of file key.cpp.