Security API for CCP: BASE64 Class Reference
BASE64 Class Reference
BASE64 class.
#include <base64.hpp>
Public Member Functions
void encode (const uint8_t *data_in, size_t length_in, char *data_out, size_t *length_out)
Function used to encode a byte array.
void decode (const char *data_in, size_t length_in, uint8_t *data_out, size_t *length_out)
Function used to decode a base64-encoded string.
Static Public Member Functions
static myerror_t test ()
Auto test function to test Base 64 conversion w.r.t. randomly generated data.
Private Member Functions
void initEncoding ()
void initDecoding ()
Static Private Member Functions
static char encodeValue (uint8_t value_in)
static int8_t decodeValue (char value_in)
Private Attributes
encode_state_t encodeState
decode_state_t decodeState
Detailed Description
Definition at line 31 of file base64.hpp.
Member Function Documentation
void BASE64::decode (const char * data_in, size_t length_in, uint8_t * data_out, size_t * length_out)
This function process the provided string to output the corresponding value in a byte array.
Parameters
data_in is the string to process.
length_in is the number of characters to consider in the string.
data_out is a byte array that will contain the decoded value.
length_out will be updated to contain the actual byte-size of the decoded value.
Definition at line 127 of file base64.cpp.
Referenced by API::loadAPI(), User::set(), Key::set(), and test().
void BASE64::encode (const uint8_t * data_in, size_t length_in, char * data_out, size_t * length_out)
This function process the provided data to output its base64-encoded value.
Parameters
data_in is an array of bytes to process.
length_in is the number of bytes in the array data_in.
data_out is a string that will contain the encoded result.
length_out will be updated to contain the actual size of the encoded result.
Definition at line 53 of file base64.cpp.
Referenced by operator<<(), API::saveAPI(), and test().
myerror_t BASE64::test () static
This function encodes and decodes some random data then checks the original value is recovered.
Returns
ERROR_UNEXPECTED if a mismatch is found
NO_ERROR if everything matches
Definition at line 5 of file base64.cpp.
References decode(), encode(), ERROR_UNEXPECTED, and NO_ERROR.
The documentation for this class was generated from the following files:
includes/base64.hpp
src/base64.cpp