Security API for CCP: User Class Reference
User Class Reference
User class.
#include <user.hpp>
Public Member Functions
User ()
Default constructor: used to create an empty User before updating it from a JSON string for instance.
User (const char login[MAX_LOGIN_LEN], const char password[MAX_PASSW_LEN], uint32_t id, role_t role)
This constructor creates a user from a login, id and role.
~User ()
User destructor.
myerror_t set (const std::string &field, const std::string &value)
This function sets the given attribute to the provided value in class User.
uint32_t getId () const
Function returning the id of the user.
const char * getLogin () const
Function returning the login of the user.
const role_t getRole () const
Function returning the role of the user.
bool hasSameLogin (const std::string &login) const
Function comparing two users' logins.
bool isCorrectPassword (const std::string &password) const
myerror_t serialize (uint8_t *tab, size_t len)
Serialize the User object to a byte array of _serializedUserSize bytes.
Static Public Attributes
static const size_t _hashPasswSize = SHA256::hashSize
Size of the hashed password.
static const size_t _serializedSize = 4 + MAX_LOGIN_LEN + _hashPasswSize + 1
Size of the serialization of a User object.
Static Private Member Functions
static void hashPassword (const char password[MAX_PASSW_LEN], uint8_t digest[_hashPasswSize])
Hashes the password.
Private Attributes
uint32_t _id
Id of the user, must be unique.
char _login [MAX_LOGIN_LEN+1]
Login of the user.
role_t _role
Role of the user.
uint8_t _password [_hashPasswSize+1]
Password (hashed password)
Friends
std::ostream & operator<< (std::ostream &os, const User &obj)
This function serializes the User class into a JSON format string.
Detailed Description
Definition at line 34 of file user.hpp.
Constructor & Destructor Documentation
User::User () inline
Definition at line 44 of file user.hpp.
User::User (const char login[MAX_LOGIN_LEN], const char password[MAX_PASSW_LEN], uint32_t id, role_t role)
Definition at line 7 of file user.cpp.
References _login, _password, and hashPassword().
User::~User ()
Definition at line 16 of file user.cpp.
Member Function Documentation
uint32_t User::getId () const
Definition at line 20 of file user.cpp.
References _id.
Referenced by API::decrypt(), API::encrypt(), API::newKey(), API::newUser(), API::unwrap(), and API::wrap().
const char * User::getLogin () const
Definition at line 25 of file user.cpp.
References _login.
const role_t User::getRole () const
Definition at line 30 of file user.cpp.
References _role.
Referenced by API::deleteUser(), and API::newUser().
bool User::hasSameLogin (const std::string & login) const
Definition at line 53 of file user.cpp.
References _login, and MAX_LOGIN_LEN.
Referenced by API::addUser().
bool User::isCorrectPassword (const std::string & password) const
brief Function comparing provided password to the user one
Definition at line 60 of file user.cpp.
References _hashPasswSize, _password, and hashPassword().
myerror_t User::set (const std::string & field, const std::string & value)
This function is for example used to construct User classes from a json_object_t.
Parameters
field is a string containing the name of the attribute
value is the value that should be set to the mentioned attribute.
Returns
NO_ERROR if no error occured
Definition at line 77 of file user.cpp.
References _hashPasswSize, _id, _login, _password, _role, BASE64::decode(), ERROR_FORMAT, and NO_ERROR.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const User & obj) friend
This function is for example used to dump a User class when saving the API in a file.
Parameters
os is an output stream in which will be send the serialized User.
obj is the User object to serialize.
Returns
the output stream given as argument.
Definition at line 35 of file user.cpp.
Field Documentation
char User::_login[MAX_LOGIN_LEN+1] private
The size of a login is at most MAX_LOGIN_LEN.
Definition at line 111 of file user.hpp.
Referenced by getLogin(), hasSameLogin(), operator<<(), serialize(), set(), and User().
The documentation for this class was generated from the following files:
includes/user.hpp
src/user.cpp