Security API for CCP: AES Class Reference
AES Class Reference
AES class.
#include <aes.hpp>
Static Public Member Functions
static void encrypt (const uint8_t key[16], const uint8_t plaintext[16], uint8_t ciphertext[16])
Function used to encrypt a plaintext into a ciphertext using AES.
static void decrypt (const uint8_t key[16], const uint8_t ciphertext[16], uint8_t plaintext[16])
Function used to decrypt a ciphertext into a plaintext using AES.
static myerror_t test ()
Auto test function to test AES implementation w.r. to few test vectors (from NIST).
Static Private Member Functions
static void keySchedule (const uint8_t key[16], uint32_t subkeys[44])
AES-128 key schedule function for encryption.
static void keySchedule_inv (const uint8_t key[16], uint32_t subkeys[44])
AES-128 key schedule function for decryption.
static void round (const uint32_t subkey[4], uint32_t state[4])
AES round function based on big tables.
static void round_inv (const uint32_t subkey[4], uint32_t state[4])
AES inverse round function based on big tables.
Static Private Attributes
static const uint32_t Te0 [256]
Big table 0 for encryption: line 0.
static const uint32_t Te1 [256]
Big table 1 for encryption: line 1.
static const uint32_t Te2 [256]
Big table 2 for encryption: line 2.
static const uint32_t Te3 [256]
Big table 3 for encryption: line 3.
static const uint32_t Te4 [256]
Big table 4 for encryption: used in last round and key schedule.
static const uint32_t Td0 [256]
Big table 0 for decryption: line 0.
static const uint32_t Td1 [256]
Big table 1 for decryption: line 1.
static const uint32_t Td2 [256]
Big table 2 for decryption: line 2.
static const uint32_t Td3 [256]
Big table 3 for decryption: line 3.
static const uint32_t Td4 [256]
Big table 4 for decryption: used in last round and key schedule.
static const uint32_t rcon [10]
Round constants for key schedule.
static const uint8_t TV_keys [2][16]
Keys used in test vectors.
static const uint8_t TV_plaintexts [2][16]
Plaintexts used in test vectors.
static const uint8_t TV_ciphertexts [2][16]
Ciphertexts used in test vectors.
Detailed Description
Definition at line 14 of file aes.hpp.
Member Function Documentation
static void AES::decrypt (const uint8_t key[16], const uint8_t ciphertext[16], uint8_t plaintext[16]) static
This function decrypts the provided ciphertext using the given key in AES-128.
Parameters
key is a 16-byte long array containing the key.
ciphertext is a 16-byte long array containing the ciphertext to decrypt.
plaintext is a 16-byte long array that will contain the decrypted message.
Referenced by API::decrypt(), API::decryptKey(), and API::unwrap().
static void AES::encrypt (const uint8_t key[16], const uint8_t plaintext[16], uint8_t ciphertext[16]) static
This function encrypts the provided plaintext using the given key in AES-128.
Parameters
key is a 16-byte long array containing the key.
plaintext is a 16-byte long array containing the plaintext to encrypt.
ciphertext is a 16-byte long array that will contain the encrypted message.
Referenced by API::encrypt(), API::protectData(), and API::wrap().
static myerror_t AES::test () static
This function uses test vectors defined in the class and test implementation versus them.
Returns
ERROR_UNEXPECTED if a mismatch is found
NO_ERROR if everything matches
The documentation for this class was generated from the following file:
includes/aes.hpp